version: '3'
services:
  app:
    build: .
    env_file:
      - .env.dev
    ports:
      - 5000:5000
    depends_on:
      - db
    command: "npm run start:dev"
  db:
    image: postgres:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust  # Just in case for simplicity
    env_file:
      - .env.dev
    ports:
      - 5432:5432