version: '3'
services:
  app:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db
    command: "npm run start:dev"
  db:
    image: postgres:latest
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: city_restaurants
    ports:
      - 5432:5432