version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.dev
    ports:
      - 5000:5000
    depends_on:
      - db
    command: "npm run start:dev"
  db:
    image: postgres:latest
    env_file:
      - .env.dev
    environment:
      POSTGRES_HOST: pg
    ports:
      - 5432:5432